app/models/BlogPost.py
from app import db


class BlogPost(db.Model):
    __tablename__ = 'blogposts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128))
    slug = db.Column(db.String(256), unique=True, index=True)
    content = db.Column(db.Text, nullable=True)
    blogcategory_id = db.Column(db.Integer, db.ForeignKey('blogcategories.id'))
    blogpoststatus_id = db.Column(db.Integer, db.ForeignKey('blogpoststatus.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    created_on = db.Column(db.DateTime)
    published_on = db.Column(db.DateTime)

    def __repr__(self):
        return '<BlogPost {!r}>'.format(self.title)

app/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog', __name__)

from . import views, errors

app/blog/views.py
from datetime import datetime
from werkzeug.contrib.atom import AtomFeed
from rfeed import *
from flask import render_template, abort, url_for, request, make_response
from app.models.BlogPost import BlogPost
from app.models.BlogCategory import BlogCategory
from app.models.Menu import Menu
from app.models.User import User
from app.models.SiteSetting import SiteSetting
from . import blog
import CommonMark


@blog.route('/blog', defaults={'page': 1})
@blog.route('/blog/<int:page>')
def the_blog(page):
    # Get all the site settings
    site_settings = SiteSetting.query.all()
    settings = {}
    for setting in site_settings:
        settings[setting.name] = setting.value

    # Get the menu we want to use for this page...
    if 'blog_menu' in settings and \
        settings['blog_menu'] is not None:
        main_menu = Menu.query.filter_by(id=int(settings['blog_menu'])).first()
    else:
        main_menu = Menu()

    blog_posts = BlogPost.query.filter(BlogPost.blogpoststatus_id == 2, \
                                    BlogPost.published_on <= datetime.utcnow())\
        .order_by(BlogPost.published_on.desc()).paginate(page, 5)
    categories = BlogCategory.query.all()

    # Markdown Parser and Renderer
    parser = CommonMark.DocParser()
    renderer = CommonMark.HTMLRenderer()

    posts = []

    for post in blog_posts.items:
        parsed = parser.parse(post.content)
        rendered = renderer.render(parsed)

        # Get username for by-line
        by = User.query.filter_by(id=post.user_id).first().username or "Unknown"

        posts.append({
            'title': post.title,
            'slug': post.slug,
            'published_on': post.published_on,
            'content': rendered,
            'by': by
        })

    # Let's return the page and menu items
    return render_template("blog/blog.html", menu=main_menu, \
                            blog_posts=blog_posts, posts=posts, \
                            categories=categories, settings=settings)


@blog.route('/blog/post/<path:slug>')
def blog_post(slug):
    # Get all the site settings
    site_settings = SiteSetting.query.all()
    settings = {}
    for setting in site_settings:
        settings[setting.name] = setting.value

    # Get the menu we want to use for this page...
    if 'blog_menu' in settings and \
        settings['blog_menu'] is not None:
        main_menu = Menu.query.filter_by(id=int(settings['blog_menu'])).first()
    else:
        main_menu = Menu()

    the_post = BlogPost.query.filter_by(slug=slug).first()

    if the_post is None or the_post.blogpoststatus_id != 2:
        abort(404)

    # Markdown Parser and Renderer
    parser = CommonMark.DocParser()
    renderer = CommonMark.HTMLRenderer()

    parsed = parser.parse(the_post.content)
    rendered = renderer.render(parsed)

    # Get username for by-line
    by = User.query.filter_by(id=the_post.user_id).first().username or "Unknown"

    post = {
        'title': the_post.title,
        'slug': the_post.slug,
        'published_on': the_post.published_on,
        'content': rendered,
        'by': by
    }

    return render_template("blog/blog_post.html", menu=main_menu, \
                            blog_post=post, category=None, settings=settings)


@blog.route('/blog/category/<path:slug>', defaults={'page': 1})
@blog.route('/blog/category/<path:slug>/<int:page>')
def blog_category(slug, page):
    category = BlogCategory.query.filter_by(slug=slug).first()

    if category is None:
        abort(404)

    # Get all the site settings
    site_settings = SiteSetting.query.all()
    settings = {}
    for setting in site_settings:
        settings[setting.name] = setting.value

    # Get the menu we want to use for this page...
    if 'blog_menu' in settings and \
        settings['blog_menu'] is not None:
        main_menu = Menu.query.filter_by(id=int(settings['blog_menu'])).first()
    else:
        main_menu = Menu()

    blog_posts = BlogPost.query.filter(BlogPost.blogcategory_id == category.id, \
                                    BlogPost.blogpoststatus_id == 2,
                                    BlogPost.published_on <= datetime.utcnow())\
        .order_by(BlogPost.published_on.desc()).paginate(page, 5)
    categories = BlogCategory.query.all()

    # Markdown Parser and Renderer
    parser = CommonMark.DocParser()
    renderer = CommonMark.HTMLRenderer()

    posts = []

    for post in blog_posts.items:
        parsed = parser.parse(post.content)
        rendered = renderer.render(parsed)

        # Get username for by-line
        by = User.query.filter_by(id=post.user_id).first().username or "Unknown"

        posts.append({
            'title': post.title,
            'slug': post.slug,
            'published_on': post.published_on,
            'content': rendered,
            'by': by
        })

    # Let's return the page and menu items
    return render_template("blog/blog.html", menu=main_menu, \
                            blog_posts=blog_posts, posts=posts, \
                            categories=categories, category=category, \
                            settings=settings)


@blog.route('/blog/feed.rss')
def blog_rss():
    root_url = '{0}blog'.format(request.url_root)
    feed = Feed(title = "CrowderSoup.com Blog",
                link = '{0}/feed.rss'.format(root_url),
                description = "This is the blog description",
                language = "en-US",
                lastBuildDate = datetime.utcnow(),
                items = [])

    # Markdown Parser and Renderer
    parser = CommonMark.DocParser()
    renderer = CommonMark.HTMLRenderer()

    blog_posts = BlogPost.query.order_by(BlogPost.published_on.desc())\
                                                                .paginate(1, 5)

    for post in blog_posts.items:
        parsed = parser.parse(post.content)
        rendered = renderer.render(parsed)

        #Get username for by-line
        by = User.query.filter_by(id=post.user_id).first().username or "Unknown"
        post_url = "{0}/{1}".format(root_url, post.slug)

        item = Item(title = post.title,
                    link = post_url,
                    description = '<![CDATA[{0}\r\n]]>'.format(rendered),
                    author = by,
                    guid = Guid(post_url),
                    pubDate = post.published_on)

        feed.items.append(item)

    response= make_response(feed.rss())
    response.headers["Content-Type"] = "application/xml"

    return response


@blog.route('/blog/feed.atom')
def blog_feed():
    root_url = '{0}/blog'.format(request.url_root)
    feed = AtomFeed('CrowderSoup.com Blog',
                    feed_url='{0}/feed.atom'.format(root_url),
                    url=root_url)

    # Markdown Parser and Renderer
    parser = CommonMark.DocParser()
    renderer = CommonMark.HTMLRenderer()

    blog_posts = BlogPost.query.order_by(BlogPost.published_on.desc())\
                                                                .paginate(1, 5)

    for post in blog_posts.items:
        parsed = parser.parse(post.content)
        rendered = renderer.render(parsed)

        # Get username for by-line
        by = User.query.filter_by(id=post.user_id).first().username or "Unknown"

        feed.add(post.title, rendered,
                 content_type='html',
                 author=by,
                 url='{0}/{1}'.format(root_url, post.slug),
                 updated=post.published_on,
                 published=post.published_on)

    return feed.get_response()

app/templates/blog/blog.html
{% extends "base.html" %}

{% block title %}{{ super() }} &mdash; {{ 'Blog' if not category else category.name }}{% endblock %}

{% block page_content %}

    <div class="page-header">
        <h1><a href="{{ url_for('blog.the_blog') }}">Blog</a> <small>Random thoughts and ramblings</small></h1>
    </div>

    <div class="row">
        <div class="col-md-9">
            <div class="post-list">
            {% for post in posts %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h3><a href="{{ url_for('blog.blog_post', slug=post.slug) }}">{{ post.title }}</a></h3>
                        </div>
                    </div>
                    <div class="panel-body">
                        {{ post.content|safe }}
                    </div>
                    <div class="panel-footer">
                        <p class="info">
                            Posted on {{ post.published_on|datetime }},
                            by {{ post.by }}
                        </p>
                    </div>
                </div>
            {% else %}
                <h3>Sorry! No posts found.</h3>
            {% endfor %}
            </div>
            <nav>
                <ul class="pager">
                    <li class="previous {{ 'disabled' if not blog_posts.has_next else '' }}">
                        {% if blog_posts.has_next %}
                            <a href="{{ url_for('blog.the_blog', page=blog_posts.next_num) }}"><span aria-hidden="true">&larr;</span> Older</a>
                        {% else %}
                            <a><span aria-hidden="true">&larr;</span> Older</a>
                        {% endif %}
                    </li>
                    <li class="next {{ 'disabled' if not blog_posts.has_prev else '' }}">
                        {% if blog_posts.has_prev %}
                            <a href="{{ url_for('blog.the_blog', page=blog_posts.prev_num) }}">Newer <span aria-hidden="true">&rarr;</span></a>
                        {% else %}
                            <a>Newer <span aria-hidden="true">&rarr;</span></a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
        </div>
        <div class="col-md-3">
            <ul class="category-list">
                {% for category in categories %}
                    <li>
                        <a href="{{ url_for('blog.blog_category', slug=category.slug) }}">{{ category.name }}</a>
                        <span class="badge">{{ category.blogposts.all()|length }}</span>
                    </li>
                {% else %}
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

app/templates/blog/blog_post.html
{% extends "base.html" %}

{% block title %}{{ super() }} &mdash; {{ blog_post.title }}{% endblock %}

{% block page_content %}
    <div class="page-header">
        <h1><a href="{{ url_for('blog.the_blog') }}">Blog</a> <small>Random thoughts and ramblings</small></h1>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="post-list">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h2>{{ blog_post.title }}</h2>
                        </div>
                    </div>
                    <div class="panel-body">
                        {{ blog_post.content|safe }}
                    </div>
                    <div class="panel-footer">
                        <p class="info">
                            Posted on {{ blog_post.published_on|datetime }},
                            by {{ blog_post.by }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}